// FIX: Import the `Differential` type to resolve the "Cannot find name 'Differential'" error.
import { VindicateCategory, Presentation, Differential, Chronicity, Demographic, BiologicalSex } from './types';

export const VINDICATE_CATEGORIES: { [key in VindicateCategory]: { name: string; description: string; color: string } } = {
  [VindicateCategory.Vascular]: { name: 'Vascular', description: 'Issues with blood vessels.', color: 'bg-rose-600' },
  [VindicateCategory.Infectious]: { name: 'Infectious', description: 'Caused by pathogens.', color: 'bg-amber-500' },
  [VindicateCategory.Neoplastic]: { name: 'Neoplastic', description: 'Cancers or tumors.', color: 'bg-purple-600' },
  [VindicateCategory.Degenerative]: { name: 'Degenerative', description: 'Progressive deterioration.', color: 'bg-slate-500' },
  [VindicateCategory.Iatrogenic]: { name: 'Iatrogenic/Intoxication', description: 'Caused by medical treatment or toxins.', color: 'bg-orange-500' },
  [VindicateCategory.Congeneric]: { name: 'Congenital', description: 'Present from birth.', color: 'bg-pink-500' },
  [VindicateCategory.Autoimmune]: { name: 'Autoimmune', description: 'Body\'s immune system attacks itself.', color: 'bg-emerald-500' },
  [VindicateCategory.Traumatic]: { name: 'Traumatic', description: 'Caused by injury.', color: 'bg-sky-600' },
  [VindicateCategory.Endocrine]: { name: 'Endocrine', description: 'Hormone-related issues.', color: 'bg-indigo-500' },
};

export const CHRONICITY_OPTIONS: Chronicity[] = [
  '1 minute – 1 hour', '1 hour – 1 day', '1 day – 7 days', '7 days – 2 weeks',
  '>2 weeks – 6 weeks', '>6 weeks – 3 months', '>3 months – 6 months', '>6 months'
];

export interface DemographicConfig {
    min: number;
    max: number;
    default: number;
    unit: 'days' | 'years';
    lockedSex?: BiologicalSex;
}

export const DEMOGRAPHIC_CONFIGS: Record<Demographic, DemographicConfig> = {
    'Neonate': { min: 1, max: 28, default: 7, unit: 'days' },
    'Pediatrics': { min: 0, max: 18, default: 10, unit: 'years' }, // 0 for < 1 year
    'Adult': { min: 18, max: 65, default: 35, unit: 'years' },
    'Geriatrics': { min: 65, max: 100, default: 75, unit: 'years' },
    'Obstetrics': { min: 18, max: 45, default: 28, unit: 'years', lockedSex: 'Female' },
};

export const getAgeGroup = (age: number, demographic: Demographic): string => {
    if (demographic === 'Neonate') return 'Neonate';
    if (demographic === 'Pediatrics') {
        if (age < 1) return 'Infant';
        if (age <= 2) return 'Toddler';
        if (age <= 5) return 'Preschooler';
        if (age <= 12) return 'Child';
        return 'Adolescent';
    }
    if (demographic === 'Adult' || demographic === 'Obstetrics') {
        if (age <= 35) return 'Young Adult';
        return 'Middle Adult';
    }
    if (demographic === 'Geriatrics') {
        if (age <= 75) return 'Young-Old';
        if (age <= 85) return 'Middle-Old';
        return 'Old-Old';
    }
    return '';
};

const defaultResources = [{ name: "McGraw Hill's Diagnosaurus 2.0", url: 'http://accessmedicine.mhmedical.com/diagnosaurus.aspx' }];

// Helper to create presentation objects from a list of names
const createPresentation = (name: string): Presentation => ({
  name,
  differentials: [], // Differentials will be generated by AI on demand
  resources: defaultResources,
});


export const SYSTEMS = [
  'Cardiovascular',
  'Dermatologic',
  'Endocrine',
  'Gastrointestinal',
  'Genitourinary',
  'Hematologic',
  'Musculoskeletal',
  'Neurologic',
  'Ocular',
  'Otolaryngologic',
  'Psychiatric',
  'Reproductive',
  'Respiratory',
  'Systemic / General',
];

export const FLASHCARD_PAIRS: { presentation: string; system: string; differentials: string[] }[] = [
  { presentation: 'Chest Pain', system: 'Cardiovascular', differentials: ['Myocardial Infarction (Heart Attack)', 'Pulmonary Embolism', 'Aortic Dissection', 'Pericarditis', 'GERD'] },
  { presentation: 'Shortness Of Breath', system: 'Respiratory', differentials: ['Asthma Exacerbation', 'COPD Exacerbation', 'Pneumonia', 'Pneumothorax', 'Heart Failure'] },
  { presentation: 'Headache', system: 'Neurological', differentials: ['Tension Headache', 'Migraine', 'Subarachnoid Hemorrhage', 'Meningitis', 'Giant Cell Arteritis'] },
  { presentation: 'Abdominal Pain', system: 'Gastrointestinal', differentials: ['Appendicitis', 'Cholecystitis', 'Pancreatitis', 'Bowel Obstruction', 'Diverticulitis'] },
  { presentation: 'Fever', system: 'Systemic / General', differentials: ['Sepsis', 'Influenza', 'Urinary Tract Infection (UTI)', 'Cellulitis', 'Meningitis'] },
  { presentation: 'Joint Pain', system: 'Musculoskeletal', differentials: ['Osteoarthritis', 'Rheumatoid Arthritis', 'Gout', 'Septic Arthritis', 'Lupus (SLE)'] },
  { presentation: 'Rash', system: 'Dermatologic', differentials: ['Urticaria (Hives)', 'Eczema (Atopic Dermatitis)', 'Psoriasis', 'Shingles (Herpes Zoster)', 'Drug Eruption'] },
  { presentation: 'Dizziness', system: 'Neurological', differentials: ['Benign Paroxysmal Positional Vertigo (BPPV)', 'Vestibular Neuritis', 'Meniere\'s Disease', 'Orthostatic Hypotension', 'Stroke (Cerebellar)'] }
];


export const PRESENTATIONS_BY_SYSTEM: { [key: string]: Presentation[] } = {
  'Cardiovascular': ['Abnormal heart sounds and murmurs', 'Blood pressure, abnormal', 'Cardiac arrest', 'Chest pain', 'Palpitations', 'Syncope and pre-syncope', 'Vascular injury'].map(createPresentation),
  'Dermatologic': ['Hair and nail complaints', 'Pruritus', 'Skin and integument conditions', 'Skin rash, macules', 'Skin rash, papules', 'Skin tumours and ulcers', 'Skin wounds', 'Urticaria, angioedema'].map(createPresentation),
  'Endocrine': ['Abnormal lipids', 'Abnormal pubertal development', 'Breast disorders', 'Calcium disorders', 'Glucose abnormal, serum/diabetes mellitus/polydipsia', 'Hirsutism, hypertrichosis', 'Menopause', 'Thyroid disease'].map(createPresentation),
  'Gastrointestinal': ['Abdominal distention', 'Abdominal injuries', 'Abdominal masses and pelvic masses', 'Abdominal pain', 'Abnormal liver function tests', 'Blood from gastrointestinal tract', 'Constipation', 'Diarrhea', 'Dysphagia', 'Hernia (abdominal wall and groin)', 'Jaundice', 'Vomiting and/or nausea'].map(createPresentation),
  'Genitourinary': ['Blood in urine (hematuria)', 'Dysuria, urinary frequency and urgency, and/or pyuria', 'Edema/anasarca/ascites', 'Incontinence', 'Kidney injury', 'Lower urinary tract symptoms', 'Potassium concentration abnormal, serum', 'Proteinuria', 'Scrotal mass', 'Scrotal pain', 'Sodium concentration abnormal, serum', 'Urinary tract injuries'].map(createPresentation),
  'Hematologic': ['Anemia', 'Bleeding, bruising', 'Coagulation abnormalities', 'Elevated hemoglobin', 'Hemoglobin level, abnormal', 'Lymphadenopathy', 'Mediastinal mass', 'Prevention of venous thrombosis', 'White blood cells, abnormalities of'].map(createPresentation),
  'Musculoskeletal': ['Back pain and related symptoms (e.g., sciatica)', 'Bone or joint injury', 'Joint pain', 'Limp in children', 'Lump or mass (musculoskeletal)', 'Neck pain', 'Non-articular musculoskeletal pain', 'Oligoarthralgia (pain in one to four joints)', 'Polyarthralgia (pain in more than four joints)'].map(createPresentation),
  'Neurologic': ['Ataxia (gait)', 'Central / peripheral neuropathic pain', 'Coma', 'Delirium', 'Diplopia', 'Dizziness and vertigo', 'Gait disturbances/ataxia', 'Headache', 'Major or mild neurocognitive disorders (dementia)', 'Movement disorders, involuntary / tic disorders', 'Numbness / tingling / altered sensation', 'Seizures / epilepsy', 'Weakness (not caused by cerebrovascular accident)'].map(createPresentation),
  'Ocular': ['Acute visual disturbance / loss', 'Chronic visual disturbance / loss', 'Eye redness', 'Strabismus and/or amblyopia', 'Visual disturbance/loss'].map(createPresentation),
  'Otolaryngologic': ['Ear pain', 'Hearing loss', 'Oral conditions', 'Sore throat and/or rhinorrhea', 'Tinnitus'].map(createPresentation),
  'Psychiatric': ['Anxiety', 'Attention, learning, and school problems', 'Depressed mood', 'Mania / hypomania', 'Mood disorders', 'Obsessive-compulsive (OCD) and related disorders', 'Personality disorders', 'Psychological trauma', 'Psychosis', 'Somatic symptoms and related disorders', 'Substance use or addictive disorders', 'Substance withdrawal', 'Suicidal behaviour'].map(createPresentation),
  'Reproductive': ['Amenorrhea, oligomenorrhea', 'Breast discharge', 'Breast masses and enlargement', 'Contraception', 'Dysmenorrhea', 'Early pregnancy loss / spontaneous abortion', 'Infertility', 'Intrapartum and postpartum care', 'Intrauterine growth restriction', 'Menstrual cycle, abnormal', 'Pelvic pain', 'Prenatal care', 'Preterm labour', 'Sexual Dysfunctions and Disorders', 'Uterine prolapse, pelvic relaxation', 'Vaginal bleeding, excessive/irregular/abnormal', 'Vaginal discharge / vulvar pruritus'].map(createPresentation),
  'Respiratory': ['Blood in sputum (hemoptysis)', 'Cough', 'Cyanosis and hypoxia', 'Dyspnea', 'Pediatric respiratory distress', 'Pleural effusion'].map(createPresentation),
  'Systemic / General': ['Acid-base abnormalities', 'Adults with developmental disabilities', 'Allergic reactions and atopy', 'Black Health', 'Burns', 'Concepts of health and its determinants', 'Disaster preparedness, emergency response, and recovery', 'Dying patients', 'Environment', 'Falls', 'Fatigue', 'Fever and hyperthermia', 'Frailty in older adults', 'Generalized pain disorders', 'Health and the climate crisis', 'Hypotension, shock', 'Hypothermia and cold-related injury', 'Immunization', 'Indigenous health', 'Outbreak management', 'Periodic health encounter/preventive health advice', 'Poisoning', 'Pre-operative medical evaluation', 'Prescribing practices', 'Quality improvement and patient safety', 'Sudden infant death syndrome (SIDS)', 'The well child and adolescent', 'Violence, family', 'Weight gain, obesity', 'Weight loss / eating disorders / anorexia', 'Work-related health issues'].map(createPresentation),
};


export const MCC_OBJECTIVES_DATA: Record<string, string> = {
  'Abdominal distension': `
Rationale
Abdominal distension may indicate the presence of serious intra-abdominal or systemic disease, but it is also a common symptom of benign disease, such as irritable bowel syndrome.

Causal Conditions (list not exhaustive)
- Ascites
  - Exudative: Low serum-ascites albumin gradient (e.g., peritoneal carcinomatosis)
  - Transudative: High serum-ascites albumin gradient (e.g., portal hypertension)
- Bowel dilatation
  - Mechanical obstruction (e.g., adhesions, volvulus)
  - Paralytic (e.g., toxic megacolon, neuropathy)
- Other
  - Abdominal mass
  - Irritable bowel syndrome
  - Organomegaly (e.g., hepatomegaly)
  - Pelvic mass (e.g., ovarian cancer)

Key Objectives
Given a patient with abdominal distension, the candidate will diagnose the cause, severity, and complications and will initiate an appropriate management plan. In particular, the candidate should be able to differentiate ascites from bowel obstruction.

Enabling Objectives
Given a patient with abdominal distention, the candidate will:
- list and interpret critical clinical findings, including features of the patient’s history and physical examination that differentiate ascites from distended bowel or mass; and the underlying cause of the ascites or bowel distention (e.g., cirrhosis, colon cancer).
- list and interpret critical investigations and imaging, including laboratory investigations and imaging (e.g., liver enzymes; paracentesis and interpretation of ascitic fluid results; abdominal imaging including 3 views of the abdomen; ultrasonography).
- construct an effective plan of management, including initiating specific therapy for ascites, mechanical or paralytic bowel obstruction, and determining whether the patient requires specialized care.
`,
'Abdominal masses and pelvic masses': `
Rationale
Abdominal or pelvic masses may be noted on physical examination or discovered incidentally on imaging. It is imperative for a physician to determine which masses require immediate investigation and treatment, and which can be safely monitored.

Causal Conditions (list not exhaustive)
- Gastrointestinal (Neoplasms, Inflammatory/infectious, Pancreatic pseudocyst)
- Genitourinary (Neoplasms, Gynecologic, Urologic)
- Lymphatic (Neoplasms, Inflammatory/infectious)
- Endocrine (Neoplasms)
- Vascular (Abdominal aortic aneurysm)
- Abdominal wall masses (e.g., sarcoma, lipoma)

Key Objectives
Given a patient with an abdominal or pelvic mass, the candidate will complete a relevant history and physical examination, and order pertinent investigations to determine the most likely diagnosis. The candidate will initiate an appropriate management plan and recognize features that indicate the need for immediate intervention.

Enabling Objectives
Given a patient with an abdominal or a pelvic mass, the candidate will:
- list and interpret critical clinical findings, including systemic symptoms and signs (e.g., weight loss, hypertension) and results of a physical examination.
- list and interpret critical investigations, including laboratory and imaging tests (e.g., ultrasonography, CT of the abdomen or pelvis, tumour markers).
- construct an effective initial management plan, including determining the need for immediate intervention or referral (e.g., abdominal aortic aneurysm) and determining the need for serial monitoring (e.g., renal cyst).
`,
'Chronic abdominal pain': `
Rationale
Chronic or recurrent abdominal pain is a common symptom with an extensive differential diagnosis. The history and physical examination frequently differentiate amongst the causative disorders.

Causal Conditions (list not exhaustive)
- Upper abdominal region (Malignancy, Ulcer, Biliary disease, Pancreatic disease, Hepatic disease, Referred cardiothoracic pain)
- Lower abdominal region (Bowel disease like IBD, Diverticular disease, IBS, Malignancy; Genitourinary disease like Dysmenorrhea, Tumors)
- Other causes (Food allergies, Constipation, Musculoskeletal, Functional)

Key Objectives
Given a patient with chronic abdominal pain, the candidate will diagnose the cause, severity, and complications, and will initiate an appropriate management plan.

Enabling Objectives
Given a patient with chronic abdominal pain, the candidate will:
- list and interpret critical clinical findings from a detailed history and physical examination.
- list and interpret critical investigations, including laboratory investigations, basic and advanced imaging, and endoscopic evaluation.
- construct an effective initial management plan, including medical, surgical, and nonpharmacologic management; determining the need for long-term follow-up; and recognizing underlying psychosocial issues.
`,
'Acute abdominal pain': `
Rationale
Acute abdominal pain is common and may result from serious intra-abdominal, intrathoracic, or retroperitoneal processes.

Causal Conditions (list not exhaustive)
- Localized pain
  - Upper abdominal region (Biliary tract disease, Pancreatitis, Peptic ulcer disease, GERD, Acute hepatitis, Splenic infarction, Referred pain, Musculoskeletal)
  - Lower abdominal region (Appendicitis, Mesenteric lymphadenitis, Diverticulitis, Incarcerated hernia, Pelvic inflammatory disease, Ectopic pregnancy, Ovarian torsion/ruptured cyst, UTI, Renal colic, IBD, Bowel obstruction)
- Diffuse pain (Generalized peritonitis, Ruptured AAA, Ischemic bowel disease, Gastroenteritis, Initial presentation of a chronic condition)

Key Objectives
Given a patient with acute abdominal pain, the candidate will diagnose the cause, severity, and complications and will initiate an appropriate management plan, identifying patients requiring emergency treatment.

Enabling Objectives
Given a patient with acute abdominal pain, the candidate will:
- list and interpret critical clinical findings, including historical features (onset, duration, location, quality of pain) and physical examination findings (abdominal exam, signs of peritonitis, rectal/genitourinary exams).
- list and interpret critical investigations, including laboratory and diagnostic imaging.
- construct an effective management plan, including determining the need for emergency care, outlining a plan for nonemergency conditions, and determining the need for specialized care.
`,
'Abdominal pain (children)': `
Rationale
Abdominal pain is a common presentation in children. While often functional, it may result from serious pathology. The cause is often age-dependent.

Causal Conditions (list not exhaustive)
- Lower abdominal pain (e.g., appendicitis, constipation, gynecologic issues)
- Flank pain (e.g., pyelonephritis, kidney stones)
- Epigastric pain (e.g., gastroesophageal reflux)
- Generalized/diffuse pain (e.g., functional, infantile colic, malabsorption)

Key Objectives
Given a pediatric patient with abdominal pain, the candidate will diagnose the cause, severity, and complications and initiate an appropriate management plan.

Enabling Objectives
Given a pediatric patient with abdominal pain, the candidate will:
- list and interpret critical findings from a detailed history and physical examination (including special manoeuvres like rebound tenderness).
- identify causes requiring a surgical procedure.
- differentiate possible psychological causes in chronic abdominal pain.
- list and interpret critical investigations (laboratory, diagnostic imaging).
- construct an effective initial management plan, determining the need for emergency intervention and appropriate management based on age, and recognizing underlying psychosocial issues.
`,
'Anorectal pain': `
Rationale
Anorectal pain can be associated with potentially serious underlying pathology, but most causes are treatable. Early identification and treatment are important to reduce morbidity.

Causal Conditions (list not exhaustive)
- Anorectal disease (IBD, Fissures, fistulas, Hemorrhoids)
- Dermatologic disease (Contact dermatitis)
- Malignancy
- Infections (Sexually transmitted, Bacterial, fungal, or parasitic)
- Trauma
- Coccygeal pain
- Complications of gastrointestinal disease

Key Objectives
Given a patient with anorectal pain, the candidate will complete a relevant history and physical examination, and order pertinent investigations to determine the most likely diagnosis and initiate an appropriate management plan.

Enabling Objectives
Given a patient with anorectal pain, the candidate will:
- list and interpret critical clinical findings, including history of pain and bleeding, and results of an appropriate examination (e.g., digital rectal examination).
- list and interpret investigations, including laboratory and endoscopic examination.
- construct an effective initial management plan, including determining the need for urgent surgical treatment, counselling on conservative treatment, discussing future preventive measures, and referring for specialized care if necessary.
`,
};